runtime: python27
api_version: 1
threadsafe: true
handlers:
  url: /(.*\.(gif|png|jpg))$
  staticfiles: dist/\1
  upload: dist/.*\.(js|css|png|jpg|svg|ttf))$
  url: /.*
  static_files: dist/index.html
  upload: dist/index.html